packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@alenaksu/json-viewer': ^2.1.2
  '@astrojs/starlight': ^0.32.2
  '@astrojs/svelte': ^7.0.5
  '@changesets/cli': ^2.28.1
  '@types/node': ^22.13.8
  astro: ^5.4.1
  astro-integration-kit: ^0.18.0
  nanostores: ^0.11.4
  sass-embedded: ^1.85.1
  sharp: ^0.33.5
  svelte: ^5.20.5
  tsup: ^8.4.0
  ts-deepmerge: ^7.0.2
  turbo: ^2.4.4

catalogs:
  peer:
    astro: ^4 || ^5
    nanostores: ^0.11.4
