packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@alenaksu/json-viewer': ^2.1.2
  '@astrojs/starlight': ^0.32.2
  '@astrojs/svelte': ^7.0.6
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.28.1
  '@types/node': ^22.13.10
  '@types/yargs': ^17.0.33
  astro: ^5.5.2
  astro-integration-kit: ^0.18.0
  create-astro: ^4.11.1
  glob: ^11.0.1
  nanostores: ^0.11.4
  sass-embedded: ^1.85.1
  sharp: ^0.33.5
  svelte: ^5.23.0
  tsup: ^8.4.0
  tsx: ^4.19.3
  ts-deepmerge: ^7.0.2
  turbo: ^2.4.4
  typescript: ^5.8.2
  vitest: ^3.0.8
  yargs: ^17.7.2

catalogs:
  peer:
    astro: ^4 || ^5
    nanostores: ^0.11.4
