packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@alenaksu/json-viewer': ^2.1.2
  '@astrojs/starlight': ^0.34.0
  '@astrojs/svelte': ^7.0.10
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.29.2
  '@types/node': ^22.14.1
  '@types/yargs': ^17.0.33
  astro: ^5.7.4
  astro-integration-kit: ^0.18.0
  create-astro: ^4.11.2
  glob: ^11.0.1
  nanostores: ^0.11.4
  sass-embedded: ^1.86.3
  sharp: ^0.34.1
  svelte: ^5.28.1
  tsup: ^8.4.0
  tsx: ^4.19.3
  ts-deepmerge: ^7.0.2
  turbo: ^2.5.0
  typescript: ^5.8.3
  vitest: ^3.1.1
  yargs: ^17.7.2

catalogs:
  peer:
    astro: ^4 || ^5
    nanostores: ^0.11.4
