packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@alenaksu/json-viewer': ^2.1.2
  '@astrojs/starlight': ^0.32.0
  '@astrojs/svelte': ^7.0.4
  '@changesets/cli': ^2.28.0
  '@types/node': ^22.13.4
  astro: ^5.3.0
  astro-integration-kit: ^0.18.0
  nanostores: ^0.11.4
  sass-embedded: ^1.85.0
  sharp: ^0.33.5
  svelte: ^5.20.2
  tsup: ^8.3.6
  ts-deepmerge: ^7.0.2
  turbo: ^2.4.2

catalogs:
  peer:
    astro: ^4 || ^5
    nanostores: ^0.11.4
