packages:
  - apps/*
  - packages/*
catalog:
  '@alenaksu/json-viewer': ^2.1.2
  '@astrojs/starlight': ^0.34.3
  '@astrojs/svelte': ^7.0.13
  '@biomejs/biome': ^1.9.4
  '@changesets/cli': ^2.29.4
  '@types/express': ^5.0.3
  '@types/node': ^22.15.18
  '@types/yargs': ^17.0.33
  astro: ^5.7.13
  astro-integration-kit: ^0.18.0
  create-astro: ^4.11.4
  express: ^5.1.0
  glob: ^11.0.2
  nanostores: ^1.0.1
  sass-embedded: ^1.88.0
  sharp: ^0.34.1
  svelte: ^5.30.1
  tsup: ^8.4.0
  tsx: ^4.19.3
  ts-deepmerge: ^7.0.3
  turbo: ^2.5.3
  typescript: ^5.8.3
  vitest: ^3.1.3
  yargs: ^17.7.2
catalogs:
  peer:
    astro: ^4 || ^5
    nanostores: ^0.11.4 || ^1
onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
